### ISSUE TITLE
How to achieve nanosecond-level accuracy？

### ISSUE THREAD

**Issue by AIllIll** [HappyZ/iw_intel8260_localization#1]
I have a little question. Can dell xps 13 provide a nanosecond-level counter? otherwise how did you solve the time measurement problem which as I know is the major obstacle of ftm.

**Comment by HappyZ** [comment]
You cannot get nanosecond-level as the hardware is not well calibrated. Check the first quoted sentence [here](https://github.com/HappyZ/iw_intel8260_localization/wiki/Enable-802.11mc-FTM-on-Intel-8260).

The best accuracy I can achieve I think is sub-meter level with some 10s of cm variance (hint: it follows a Gaussian/Normal distribution). What you could do is to calibrate the measurements by fitting a curve and understand your hardware capability (I have included mine in `libMeasurement.py`). Among four laptops I have tested the accuracy is very consistent. It should do better if we find a way to calibrate it at the hardware level.

**Comment by HappyZ** [comment]
Ah sorry I thought you were wondering about picosecond-level ranging.. even though I was typing about nanseconds.. lately got too many questions on that.. we can discuss via email.
